### ISSUE TITLE
ANALYSIS_COMPARE fails when OBS not plotted

### ISSUE THREAD

**Issue by kirenbahm** [kirenbahm/ENP_TOOLS#5]
The main script ANAYSIS_COMPARE.m works when plotting model results alongside observed data. However, when the user selects to  NOT plot the observed data (just the model results), the script fails.  The switch to turn off plotting of the observed data is around line 147 in ANALYSIS_COMPARE.m:
`INI.INCLUDE_OBSERVED      = 1; % Include observed in the output figs and tables.`

The place(s) in the script where this causes problems need to be found and fixed, so the user can plot model data without also plotting obs data.

Some info that might be helpful to know:  in the scripts we save obs data in a separate structure from model data at some times, and at other times they are combined into the same array. When they are in the same array, the obs data is usually the first element in that array (especially for plotting).

**Comment by LAGO-Support** [comment]
Discovered Source of error.
When A2_generate_extracted_stat.m at line 102, throws an error when calling remove_nan.
As such STATION.TS_NAN is never instantiated when there is no observed data.
The observed data is skipped properly in subsequent functions until the Latex report is being written.
When generate_latex_files_by_area.m at line 12 calls getMapAreas.m, it throws an error, whose cause is due to that missing variable.
